## NumPy

In [48]:
import numpy as np
# просто сидим генератор случайных чисел, чтобы набор чисел был всегда одинаковый
np.random.seed(0)

In [49]:
# Создание массивов
# One-dimensional array
x1 = np.random.randint(10, size=6)
# Two-dimensional array
x2 = np.random.randint(10, size=(3, 4))
# Three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))

Параметр `size` задаёт размерность массива. Причем сначала задаётся количество строк. Например, размерность `size=(3, 4, 5` означает, что в массиве будет 3 строки, в каждой строке будут 4 строки и каждая строка будет содержать 5 элементов. Это хорошо видно при распечатке массива `np.random.randint(10, size=(3, 4, 5))`

In [50]:
print(x1)
print("-" * 50)
print(x2)
print("-" * 50)
print(x3)

[5 0 3 3 7 9]
--------------------------------------------------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
--------------------------------------------------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


## Свойства массивов

`ndim` - количество измерений (многомерность массива)   
`shape` - форма массива (размер каждого измерения)   
`size` - общее количество элементов массива    
`dtype` - тип элементов массива    
`itemsize` - размер одного элемента массива в байтах    
`nbytes` - размер всего массива в байтах

In [51]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x2 dtype: ", x2.dtype)
print("x3 itemsize ", x3.itemsize, " bytes")
print("x3 nbytes ", x3.nbytes, " bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x2 dtype:  int64
x3 itemsize  8  bytes
x3 nbytes  480  bytes


## Доступ к элементам

### Чтение

In [52]:
# Одномерный массив
x1[3]

3

In [53]:
# Многомерный массив. Схема доступа: строка1, ... строкаN, элементN
x3[1, 1, 2]

3

### Запись

In [54]:
print(x1)
x1[2] = 4
print(x1)

[5 0 3 3 7 9]
[5 0 4 3 7 9]


#### Запись элемента другого типа

При записи элементов другого типа они будут приведены к типу элементов массива. **Имейте ввиду, что при этом может происходить потеря точности!**

In [55]:
x4 = np.array([True, False, True, True])
print(x4)
x4[1] = 15
print(x4)

[ True False  True  True]
[ True  True  True  True]


### Slicing

In [56]:
# одномерные массивы
print(x1)
x1[1:3]

[5 0 4 3 7 9]


array([0, 4])

In [57]:
## многомерные массивы
print(x2)
x2[:2, :3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[3, 5, 2],
       [7, 6, 8]])

#### Доступ к колонкам или строка в многомерном массиве

In [58]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [59]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


### Запись в подмассивы (слайсы)

**В отличие от Python, подмассивы (слайсы) `NumPy` предоставляют возможность записывать непосредственно в массив!!!**

In [60]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [61]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [62]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [63]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays