# NumPy

In [20]:
import numpy as np
# просто сидим генератор случайных чисел, чтобы набор чисел был всегда одинаковый
np.random.seed(0)

In [21]:
# Создание массивов
# One-dimensional array
x1 = np.random.randint(10, size=6)
# Two-dimensional array
x2 = np.random.randint(10, size=(3, 4))
# Three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))

Параметр `size` задаёт размерность массива. Причем сначала задаётся количество строк. Например, размерность `size=(3, 4, 5` означает, что в массиве будет 3 строки, в каждой строке будут 4 строки и каждая строка будет содержать 5 элементов. Это хорошо видно при распечатке массива `np.random.randint(10, size=(3, 4, 5))`

In [22]:
print(x1)
print("-" * 50)
print(x2)
print("-" * 50)
print(x3)

[5 0 3 3 7 9]
--------------------------------------------------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
--------------------------------------------------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


## Свойства массивов

`ndim` - количество измерений (многомерность массива)   
`shape` - форма массива (размер каждого измерения)   
`size` - общее количество элементов массива    
`dtype` - тип элементов массива    
`itemsize` - размер одного элемента массива в байтах    
`nbytes` - размер всего массива в байтах

In [23]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x2 dtype: ", x2.dtype)
print("x3 itemsize ", x3.itemsize, " bytes")
print("x3 nbytes ", x3.nbytes, " bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x2 dtype:  int64
x3 itemsize  8  bytes
x3 nbytes  480  bytes


## Доступ к элементам

### Чтение

In [24]:
# Одномерный массив
x1[3]

3

In [25]:
# Многомерный массив. Схема доступа: строка1, ... строкаN, элементN
x3[1, 1, 2]

3

### Запись

In [26]:
print(x1)
x1[2] = 4
print(x1)

[5 0 3 3 7 9]
[5 0 4 3 7 9]


#### Запись элемента другого типа

При записи элементов другого типа они будут приведены к типу элементов массива. **Имейте ввиду, что при этом может происходить потеря точности!**

In [27]:
x4 = np.array([True, False, True, True])
print(x4)
x4[1] = 15
print(x4)

[ True False  True  True]
[ True  True  True  True]


### Slicing

In [28]:
# одномерные массивы
print(x1)
x1[1:3]

[5 0 4 3 7 9]


array([0, 4])

In [29]:
## многомерные массивы
print(x2)
x2[:2, :3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[3, 5, 2],
       [7, 6, 8]])

#### Доступ к колонкам или строка в многомерном массиве

In [30]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [31]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


### Запись в подмассивы (слайсы)

**В отличие от Python, подмассивы (слайсы) `NumPy` предоставляют возможность записывать непосредственно в массив!!!**

Подмассив представляет собой `no-copy view` исходного массива, а не новый массив.

In [32]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [33]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [34]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [35]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [36]:
# Можно воспользоваться методом `copy()`
# Если изменить копию, то оригинальный массив останется нетронутым!!!
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


## Изменение формы массива

In [41]:
grid = np.arange(1, 10)
print(grid)
grid2 = grid.reshape((3, 3))
print(grid2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
## Еще один способ изменить форму массива - это использовать ключевое слово `np.newaxis` в операции среза
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [44]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [45]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [46]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Соединение и разделение массивов

### Соединение массивов

In [51]:
# Метод `concatenate`
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [91, 92, 93]
np.concatenate((x, y, z))

array([ 1,  2,  3,  3,  2,  1, 91, 92, 93])

In [52]:
# `concatenate` работает и на многомерных массивах

In [53]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [54]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для работы с многомерными массивами, особенно с различной размерностью, намного более понятно использовать методы `np.vstack` (вертикальный стек) и `np.hstack` (горизонтальный стек).

In [57]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Разделение массивов

Разделение осуществляется функциями `np.split`, `np.hsplit`, и `np.vsplit`. Для каждой из этих функций мы можем передать список индексов, задающих точки разделения, а именно позиции в массиве, которые станут началами новых массивов.    
**Для N точек разделения всегда получается N+1 подмассивов.**

In [60]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # индексы 3 и 5 в исходном массиве являются точками разделения на массивы
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Функции `np.hsplit` и `np.vsplit` работают следующим образом:

In [64]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [66]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Вычисления на массивах, универсальные функции